/* code generated by JNAConvert -- DO NOT EDIT */
package types.structs;
import com.sun.jna.Structure;
@SuppressWarnings("all")
/** Structure test */
public class Test extends Structure implements Structure.ByValue
{
    /** i field */
    public int i;
}
